name: 🚀 Deploy User Function to Azure

on:
  push:
    paths:
      - 'services/user-service/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 🚀 Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: serverless-platform-user
          package: ./services/user-service
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
